// Code generated by protoc-gen-go. DO NOT EDIT.
// source: createAccount.proto

package model

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateAccount struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RequestId            string   `protobuf:"bytes,2,opt,name=requestId,proto3" json:"requestId,omitempty"`
	Creator              string   `protobuf:"bytes,3,opt,name=creator,proto3" json:"creator,omitempty"`
	CreateDate           string   `protobuf:"bytes,4,opt,name=createDate,proto3" json:"createDate,omitempty"`
	Approver             string   `protobuf:"bytes,5,opt,name=approver,proto3" json:"approver,omitempty"`
	UpdateDate           string   `protobuf:"bytes,6,opt,name=updateDate,proto3" json:"updateDate,omitempty"`
	Status               string   `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	Content              string   `protobuf:"bytes,8,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAccount) Reset()         { *m = CreateAccount{} }
func (m *CreateAccount) String() string { return proto.CompactTextString(m) }
func (*CreateAccount) ProtoMessage()    {}
func (*CreateAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_39d5aa8a85c461aa, []int{0}
}

func (m *CreateAccount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAccount.Unmarshal(m, b)
}
func (m *CreateAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAccount.Marshal(b, m, deterministic)
}
func (m *CreateAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAccount.Merge(m, src)
}
func (m *CreateAccount) XXX_Size() int {
	return xxx_messageInfo_CreateAccount.Size(m)
}
func (m *CreateAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAccount.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAccount proto.InternalMessageInfo

func (m *CreateAccount) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CreateAccount) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *CreateAccount) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *CreateAccount) GetCreateDate() string {
	if m != nil {
		return m.CreateDate
	}
	return ""
}

func (m *CreateAccount) GetApprover() string {
	if m != nil {
		return m.Approver
	}
	return ""
}

func (m *CreateAccount) GetUpdateDate() string {
	if m != nil {
		return m.UpdateDate
	}
	return ""
}

func (m *CreateAccount) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *CreateAccount) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type CreateAccountList struct {
	List                 []*CreateAccount `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *CreateAccountList) Reset()         { *m = CreateAccountList{} }
func (m *CreateAccountList) String() string { return proto.CompactTextString(m) }
func (*CreateAccountList) ProtoMessage()    {}
func (*CreateAccountList) Descriptor() ([]byte, []int) {
	return fileDescriptor_39d5aa8a85c461aa, []int{1}
}

func (m *CreateAccountList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAccountList.Unmarshal(m, b)
}
func (m *CreateAccountList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAccountList.Marshal(b, m, deterministic)
}
func (m *CreateAccountList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAccountList.Merge(m, src)
}
func (m *CreateAccountList) XXX_Size() int {
	return xxx_messageInfo_CreateAccountList.Size(m)
}
func (m *CreateAccountList) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAccountList.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAccountList proto.InternalMessageInfo

func (m *CreateAccountList) GetList() []*CreateAccount {
	if m != nil {
		return m.List
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateAccount)(nil), "model.CreateAccount")
	proto.RegisterType((*CreateAccountList)(nil), "model.CreateAccountList")
}

func init() { proto.RegisterFile("createAccount.proto", fileDescriptor_39d5aa8a85c461aa) }

var fileDescriptor_39d5aa8a85c461aa = []byte{
	// 287 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x50, 0xcd, 0x4a, 0xf3, 0x40,
	0x14, 0x6d, 0xda, 0x34, 0x4d, 0xef, 0xc7, 0x57, 0x70, 0x94, 0x32, 0x44, 0x91, 0x92, 0x55, 0x56,
	0x53, 0xa8, 0xbb, 0x82, 0x0b, 0x51, 0x17, 0x82, 0xab, 0xbc, 0x41, 0x9a, 0x5c, 0x43, 0x20, 0xcd,
	0xc4, 0x99, 0x1b, 0xc1, 0x37, 0xf0, 0x45, 0x7d, 0x0f, 0xc9, 0x4d, 0x63, 0x1b, 0xa8, 0xcb, 0xf3,
	0x37, 0x73, 0xee, 0x81, 0xcb, 0xd4, 0x60, 0x42, 0xf8, 0x90, 0xa6, 0xba, 0xa9, 0x48, 0xd5, 0x46,
	0x93, 0x16, 0xd3, 0xbd, 0xce, 0xb0, 0x0c, 0xae, 0x73, 0xad, 0xf3, 0x12, 0xd7, 0x4c, 0xee, 0x9a,
	0xb7, 0x35, 0xee, 0x6b, 0xfa, 0xec, 0x3c, 0xe1, 0xb7, 0x03, 0xff, 0x1f, 0x4f, 0xb3, 0x62, 0x01,
	0xe3, 0x22, 0x93, 0xce, 0xca, 0x89, 0xe6, 0xf1, 0xb8, 0xc8, 0xc4, 0x0d, 0xcc, 0x0d, 0xbe, 0x37,
	0x68, 0xe9, 0x25, 0x93, 0x63, 0xa6, 0x8f, 0x84, 0x90, 0x30, 0xe3, 0xaf, 0xb5, 0x91, 0x13, 0xd6,
	0x7a, 0x28, 0x6e, 0x01, 0xba, 0x52, 0x4f, 0x09, 0xa1, 0x74, 0x59, 0x3c, 0x61, 0x44, 0x00, 0x7e,
	0x52, 0xd7, 0x46, 0x7f, 0xa0, 0x91, 0x53, 0x56, 0x7f, 0x71, 0x9b, 0x6d, 0xea, 0xac, 0xcf, 0x7a,
	0x5d, 0xf6, 0xc8, 0x88, 0x25, 0x78, 0x96, 0x12, 0x6a, 0xac, 0x9c, 0xb1, 0x76, 0x40, 0xdc, 0x46,
	0x57, 0x84, 0x15, 0x49, 0xff, 0xd0, 0xa6, 0x83, 0xe1, 0x3d, 0x5c, 0x0c, 0xce, 0x7c, 0x2d, 0x2c,
	0x89, 0x08, 0xdc, 0xb2, 0xb0, 0x24, 0x9d, 0xd5, 0x24, 0xfa, 0xb7, 0xb9, 0x52, 0xbc, 0x97, 0x1a,
	0xf8, 0x62, 0x76, 0x6c, 0xbe, 0x1c, 0x58, 0x0c, 0x78, 0x2b, 0xb6, 0xe0, 0xc7, 0x98, 0x17, 0x96,
	0xd0, 0x88, 0xb3, 0xd1, 0x60, 0xa9, 0xba, 0xe5, 0x55, 0xbf, 0xbc, 0x7a, 0x6e, 0x97, 0x0f, 0x47,
	0x62, 0x0b, 0x2e, 0x17, 0xf8, 0xc3, 0x11, 0xc8, 0x73, 0xef, 0xb5, 0x89, 0x70, 0xb4, 0xf3, 0xd8,
	0x7b, 0xf7, 0x13, 0x00, 0x00, 0xff, 0xff, 0xd4, 0x0f, 0x14, 0x9e, 0xf3, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CreateAccountsClient is the client API for CreateAccounts service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CreateAccountsClient interface {
	Register(ctx context.Context, in *CreateAccount, opts ...grpc.CallOption) (*empty.Empty, error)
	List(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*CreateAccountList, error)
}

type createAccountsClient struct {
	cc *grpc.ClientConn
}

func NewCreateAccountsClient(cc *grpc.ClientConn) CreateAccountsClient {
	return &createAccountsClient{cc}
}

func (c *createAccountsClient) Register(ctx context.Context, in *CreateAccount, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/model.CreateAccounts/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *createAccountsClient) List(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*CreateAccountList, error) {
	out := new(CreateAccountList)
	err := c.cc.Invoke(ctx, "/model.CreateAccounts/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CreateAccountsServer is the server API for CreateAccounts service.
type CreateAccountsServer interface {
	Register(context.Context, *CreateAccount) (*empty.Empty, error)
	List(context.Context, *empty.Empty) (*CreateAccountList, error)
}

// UnimplementedCreateAccountsServer can be embedded to have forward compatible implementations.
type UnimplementedCreateAccountsServer struct {
}

func (*UnimplementedCreateAccountsServer) Register(ctx context.Context, req *CreateAccount) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (*UnimplementedCreateAccountsServer) List(ctx context.Context, req *empty.Empty) (*CreateAccountList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}

func RegisterCreateAccountsServer(s *grpc.Server, srv CreateAccountsServer) {
	s.RegisterService(&_CreateAccounts_serviceDesc, srv)
}

func _CreateAccounts_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAccount)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CreateAccountsServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/model.CreateAccounts/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CreateAccountsServer).Register(ctx, req.(*CreateAccount))
	}
	return interceptor(ctx, in, info, handler)
}

func _CreateAccounts_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CreateAccountsServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/model.CreateAccounts/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CreateAccountsServer).List(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _CreateAccounts_serviceDesc = grpc.ServiceDesc{
	ServiceName: "model.CreateAccounts",
	HandlerType: (*CreateAccountsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _CreateAccounts_Register_Handler,
		},
		{
			MethodName: "List",
			Handler:    _CreateAccounts_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "createAccount.proto",
}
